### PR TITLE
merge & rebase for pinpox SSO

### PR DESCRIPTION
**Pull request by m4w0lf**
Hi @pinpox,
I rebased you branch and I aligned it with current main on dani-garcia/vaultwarden.

Docker container builds successfully.

Can you help me to configure and test it?

### CODE REVIEW

**Comment by pinpox** [comment]
Nice, thanks for working on this! What do you need help with exactly? Configuration is pretty straightforward with any Auth provider that supports OpenID connect. I tested it with Gitea specifically

**Comment by m4w0lf** [comment]
I could not find the frontend part to configure the connection to the issuer, nor the step needed.
Maybe I can reach you by email / discord for help on configuring versus keycloak?

Maybe we can also talk how to appropriate squash and merge, like suggested here -> https://github.com/dani-garcia/vaultwarden/pull/2449#issuecomment-1266776540

**Comment by blaubaer** [comment]
Dear participants,

From the whole conversation I'm not fully sure about the current state, therefore: I can support the finalization of this PR in some way? By testing or whatever? I like to support the finalization of that topic as soon as possible, because it will boost a lot of professional contexts. 😀

**Comment by KramNamez** [comment]
Seconding blaubaer - this is the only blocker keeping us from adopting Vaultwarden and I'd like to help make this happen, if at all possible.

**Comment by ROFISH** [comment]
Thirding! If there is testing or some light additional work, I'm happy to help since this is the blocker we need to resolve before deployment.

**Comment by Eweol** [comment]
Is there any chance that this will be part of next release?

**Comment by Rutkv0** [comment]
Any updates?

**Comment by himself1985** [comment]
Sehr geehrte Damen und Herren,


ich befinde mich aktuell im Urlaub und bin bis einschließlich 27.01.2023 nicht zu erreichen.
Ihre eMails werden nicht weitergeleitet.


In dringenden Fällen wenden Sie sich bitte an meinen Kollegen:


Matthias ***@***.***
i.A. Jonas Zimmermann
IT-Abteilung

GREIFF Mode GmbH & Co. KG
Memmelsdorfer Strasse 250
96052 Bamberg
Deutschland





+49 951 405 238
***@***.***
greiff.de


  Visitenkarte als vCard




 
USt-IdNr.: DE 249 822 002 | Kommanditgesellschaft: Sitz Bamberg | Amtsgericht Bamberg HRA 10668 
Persönlich haftende Gesellschafterin: GREIFF Mode Verwaltungs GmbH | Sitz Bamberg HRB 653  
Geschäftsführer: Jens Möller

**Comment by blaubaer** [comment]
@m4w0lf Can you please at least tell us if you abandon this topic or if you're still planning to work on it OR if we (the community) needs to finds someone else to work on it?

**Comment by bmunro-peralex** [comment]
So i'll be creating another PR shortly that implements this. I got it working on my gitlab instance. Just trying to finalize the creating of users if they don't exist directly from the SSO call, instead of having the users need to be created first.

**Pull request closed without merging**
