### PR TITLE
Some fixes for the new mobile apps

### PR DESCRIPTION
**Pull request by dani-garcia**
The new mobile apps are going to send some values slightly differently and will expect some other values to be there, while we previously weren't sending them. This should fix those issues, at least for Android.

Note that we will still need to go through with #4386 for the apps to work correctly.

### CODE REVIEW

**Review by BlackDex — APPROVED** [review]

**Comment by BlackDex** [comment]
Is #4386 mandatory for the new Android/iOS apps to work on the new releases?
Or will they still work for now, but will become an issue in a few months?

**Comment by dani-garcia** [comment]
It will be required for the new native mobile apps, whenever they get released, as they don't have the backwards compatibility support for server responses using PascalCase. So not super urgent but we probably don't want to wait too long.

**Comment by BlackDex** [comment]
Indeed. But at least good to know it's not needed for the current versions.
Ill see if i can verify that PR soon.

**Comment by AkechiShiro** [comment]
Is this going to be released soon ? I cannot use the mobile app with my vaultwarden instance at the moment due to version mismatch I think.

**Comment by farfromrefug** [comment]
@AkechiShiro where can we get those new apps ? Is the source code on github?

**Comment by BlackDex** [comment]
What i know is that it is still in a alpha stage, and not publicly available. But when ready it will be visible on GitHub as far as i known. We just have to wait.

**Comment by AkechiShiro** [comment]
@farfromrefug there is no vaultwarden app I believe, I think the changes here are made in order to be compatible with an updated Bitwarden app ? But the release containing this new pull request hasn't gone out yet AFAIK

**Comment by farfromrefug** [comment]
@AkechiShiro you arr right I was talkin about thé new bitwarden apps

**Comment by AkechiShiro** [comment]
@farfromrefug the new one is most likely released in the Bitwarden repository

**Pull request merged**
