### PR TITLE
making SMTP force TLS description in admin panel clearer

### PR DESCRIPTION
**Pull request by jonathanmmm**
fixes https://github.com/dani-garcia/vaultwarden/discussions/1639

### CODE REVIEW

**Comment by BlackDex** [comment]
Thx for your contribution. But i think i will change the logic of that will not break other config. If that is not possible, then this comment could be useful.

**Comment by jonathanmmm** [comment]
Ok, if I only checked force TLS I got an error, if this is true for everyone, then no configs can be destroyed, as they wouldn't work.

**Comment by jonathanmmm** [comment]
Yes, you have to make both set to true still be working, but optional and in the future only one has to be set.
Maybe in the admin panel this can be archieved through a 3 choose button style (either no encryption, implicit or explicit), how this is solved via config file, I don't know right now. Maybe through a SMTP_security_level from 0 to 2 and still accept old flags set.

**Comment by BlackDex** [comment]
I have changed the logic in my PR #1670.

**Comment by jonathanmmm** [comment]
Great, ok, I closed my PR

**Pull request closed without merging**
