### PR TITLE
Update Vaultwarden Logo's

### PR DESCRIPTION
**Pull request by BlackDex**
Updated the logo's so the `V` is better visible.
Also the cog it self is better now, the previous version wasn't fully round. These versions also are used with the PR to update the web-vault and use these logo's.

Also updated the images in the static folder.

### CODE REVIEW

**Comment by stefan0xC** [comment]
@dani-garcia can you maybe also update the Logo of [Vaultwarden Discourse](https://vaultwarden.discourse.group/)? 


vaultwarden-logo

And I've read somewhere that you can also use a different logo for dark mode which is currently almost invisible.
vaultwarden-discourse-darkmode

So it would be nice if you could change it to the white variant:
vaultwarden-logo-white

**Comment by dani-garcia** [comment]
@stefan0xC Should be fixed now!

**Comment by stefan0xC** [comment]
@dani-garcia Thanks. I think the smaller white logo is missing the holes:
discourse-white-logo

Could be an artifact of svg to png conversion, so maybe if you upload it as png directly it will work better?
vaultwarden-icon-white
vaultwarden-icon

**Comment by stefan0xC** [comment]
For [#vaultwarden:matrix.org](https://matrix.to/#/#vaultwarden:matrix.org) there would also be a white background and a border:
vaultwarden-icon-with-bg-and-border


I've created it with 
```
convert -density 1200 -resize 412x412 vaultwarden-icon{.svg,-with-bg.png}
convert -bordercolor white -border 50 vaultwarden-icon-with-bg{,-and-border}.png
```

**Comment by BlackDex** [comment]
I changed the avatar on matrix just now.

**Pull request merged**
