### PR TITLE
allow editing/unhiding by group

### LINKED ISSUE #2989: Group members cannot add new entries to collection on testing-branch
### Subject of the issue
When using the groups-feature on the testing-branch, a "regular" group-member (non-manager) cannot create any entries in a collection, that is given access to via groups.

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.26.0-d0b53a6a
* Web-vault version: v2022.11.2
* Running within Docker: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: PostgreSQL
* Database version: PostgreSQL 13.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Steps to reproduce
1. Create an organisation (or use existing)
2. Add another user "U" (any name is fine) to the organisation (as a regular user)
3. Create(or use existing) collection "C" (any name is fine)
4. Create(or use existing) group "G" (any name is fine)
4.1. Give permission of that collection "C" to the group "G"
4.2. Assign the user "U" to the group "G"
4.3. Make sure that the user "U" does **not** have direct permission on the collection "C". In other words: the permission should be configured via the group only!
5. Login as user "U"
5.1. Add a new entry to the collection "C"

### Expected behavior
The entry should be added to the collection.

### Actual behavior
An error toast appears in the top right: "You lack the necessary permissions to perform this action."

### PR DESCRIPTION
**Pull request by farodin91**
Fixes #2989

### CODE REVIEW

**Comment by farodin91** [comment]
I wanted to fix and saw some other query's that are huge. I find it hard to debug query's that have multiple joins. This way you can reuse some code. The location is probably wrong, I will fix this it by moving directly into collections.

**Comment by farodin91** [comment]
@BlackDex  I changed it to one query by using find_by_uuid_and_user.

**Review by BlackDex — APPROVED** [review]
While I'm still in favor of changing the DB Schema around the whole group handling to make it less complex, probably with a bit less of normalization, this _quick fix_ does provide a good way of allowing this feature to be tested a bit further by more people and give us time to think about a proper and better solution.

So, ill approve this PR, with the side note that i think we do need to rework this feature to be less complex.

**Comment by BlackDex** [comment]
@farodin91 Could you try to rebase 😄 .

**Comment by farodin91** [comment]
@BlackDex  Rebased.

Do i have write in the discussion for re license thread?

**Comment by BlackDex** [comment]
> @BlackDex Rebased.
> 
> Do i have write in the discussion for re license thread?

That would be nice :)

**Review by dani-garcia — APPROVED** [review]

**Comment by bendem** [comment]
Awesome, and thank you for favoring performance. It is indeed a bit harder to read, but users and database admins thank you for it (re #1402).

**Pull request merged**
