### PR TITLE
fix: Allow admin page working on subpaths

### PR DESCRIPTION
**Pull request by GeekCornerGH**
Hi everyone,
I made this patch to fix this bug on the admin page when using subpath:
image

Have a great day

### CODE REVIEW

**Comment by BlackDex** [comment]
Thanks for the PR, but this is really not needed, since if you configure the `DOMAIN` variable correctly it will just work fine.

Your changes do not take into account multiple sub-paths for example, while it will work the way it already was.

I'm not going to approve this one.

**Comment by GeekCornerGH** [comment]
> Thanks for the PR, but this is really not needed, since if you configure the `DOMAIN` variable correctly it will just work fine.
> 
> Your changes do not take into account multiple sub-paths for example, while it will work the way it already was.
> 
> I'm not going to approve this one.

I had DOMAIN env variable actually

**Review by williamdes — APPROVED** [review]
That should work

**Comment by BlackDex** [comment]
> > Thanks for the PR, but this is really not needed, since if you configure the `DOMAIN` variable correctly it will just work fine.
> > Your changes do not take into account multiple sub-paths for example, while it will work the way it already was.
> > I'm not going to approve this one.
> 
> I had DOMAIN env variable actually

Then something else would be wrong, since it works just fine for me.
Also make sure there is no config.json, amd if there is, then adjust the domain there too.

That whole `{{urlpath}}` is the special part to support these sub-paths, so that would be strange to remove and replace.

**Comment by BlackDex** [comment]
> That should work

It will only work with one sub-path level, not two like `/secret/vaultwarden`, then it will break again probably.
Also, it's just bad to always use `../` i think.

**Comment by GeekCornerGH** [comment]
> > That should work
> 
> It will only work with one sub-path level, not two like `/secret/vaultwarden`, then it will break again probably. Also, it's just bad to always use `../` i think.

Ah yes didn't thought about that.

**Comment by GeekCornerGH** [comment]
Sent a message on Matrix, maybe you will be able to help me

**Comment by BlackDex** [comment]
Since it's fixed now, let's close this

**Pull request closed without merging**
