### PR TITLE
Installation Procedure and Database Export Script

### PR DESCRIPTION
**Pull request by NicolasW-7**
I have tried to create an installation procedure that is easily reusable and has already been tested in a professional environment.
The goal is to try to enhance the Vaultwarden experience and provide a script for database export in case of emergency recovery. I leave it to you to assess the relevance of my proposal.

Nicolas

### CODE REVIEW

**Comment by BlackDex** [comment]
First of all, thanks for taking the effort of creating these articles.

I'm not a fan of adding this to the repo.

This is more of a Wiki article of which we already have a few of.
It might be better to update existing articles or create new ones using this information.

**Comment by NicolasW-7** [comment]
Thank you for your response and for the time you have given me. Do you have a link or a repository to suggest where I can upload this procedure and script ?

**Comment by BlackDex** [comment]
It isn't a repo in that sense. You can just add or adjust articles here: https://github.com/dani-garcia/vaultwarden/wiki

**Comment by smainz** [comment]
A very comprehensive and detailed guide, but unfortunately no longer up to date.

A web socket is still configured and the admin token is not an aragon2 token.

**Comment by BlackDex** [comment]
Closing this in favor of adding these to the wiki

**Pull request closed without merging**
