### PR TITLE
Some refactoring and optimizations

### PR DESCRIPTION
**Pull request by BlackDex**
- Refactored several code to use more modern syntax
- Made some checks a bit more strict
- Updated crates

### CODE REVIEW

**Review by dani-garcia — APPROVED** [review]

**Comment by gaby** [comment]
@dani-garcia @BlackDex This should be submitted as a CVE.

**Comment by BlackDex** [comment]
I'm not sure if we really should report a CVE to be honest.
I'm not against it though, but also not sure if this would really add any benefit either.

It will probably take a long time for it to be requested and granted, since for one i have never done that my self before, and what i hear is that it is a long process.

**Comment by gaby** [comment]
@BlackDex With GitHub it takes 1-2 days. You do it through that URL I posted above. GitHub will handle adding the entry to the registries, assigning a cve #, etc.

**Comment by BlackDex** [comment]
Ok. fine by me

**Comment by dani-garcia** [comment]
For future reference, the advisory lives here, but it's private at the moment while waiting for Github to assign it a CVE:

https://github.com/dani-garcia/vaultwarden/security/advisories/GHSA-g65h-982x-4m5m

I'll update here again once that process is done and the CVE is public.

**Comment by dani-garcia** [comment]
Well that didn't take long at all, advisory and CVE are public at https://github.com/dani-garcia/vaultwarden/security/advisories/GHSA-g65h-982x-4m5m

**Comment by gaby** [comment]
@dani-garcia Thank you 💪

**Pull request merged**
