### PR TITLE
Resolve uninlined_format_args clippy warnings

### PR DESCRIPTION
**Pull request by BlackDex**
The upcomming release of Rust 1.67.0 will warn on `uninlined_format_args`.
This PR resolves that by inlining all these items. It also looks nicer.

Also added a `clippy.toml` which indicates the **MSRV** to prevent clippy suggests which could break the **MSRV** version compile.

### CODE REVIEW

**Review by tessus — COMMENTED** [review]
You missed the following 2, or was this on purpose?

https://github.com/dani-garcia/vaultwarden/blob/f34d7e37c359ea46f5023916ec4d977db5c17c0b/src/main.rs#L310

https://github.com/dani-garcia/vaultwarden/blob/f34d7e37c359ea46f5023916ec4d977db5c17c0b/src/main.rs#L319

P.S.: I didn't check the entire code base, but these 2 caught my eye.

**Comment by BlackDex** [comment]
Well, those are not triggered by that clippy check.

While there are more then just those two which can also be converted, they aren't causing a clippy warning.

That doesn't mean we shouldn't change them though.

**Comment by tessus** [comment]
I am new to Rust, so why don't they trigger a warning? I did not see a compiler directive to not check that part of the code, or maybe I missed it?

**Comment by BlackDex** [comment]
Those macros aren't part of the rust eco system it self, but provide by custom macros. `format!` and `println!` for example are.

**Comment by tessus** [comment]
I see. Thanks for the info.

**Pull request merged**
