### PR TITLE
Some Admin Interface updates

### PR DESCRIPTION
**Pull request by BlackDex**
- Updated datatables
- Added NTP Time check
- Added Collections, Groups and Events count for orgs
- Renamed `Items` to `Ciphers`
- Some small style updates

### CODE REVIEW

**Review by dani-garcia — APPROVED** [review]

**Comment by jjlin** [comment]
I'm not sure renaming `Items` to `Ciphers` in the UI is an improvement. IMO, this is an overly technical term that may cause confusion, and Bitwarden itself uses the "items" term in their UI and user-facing docs.

Also, you might consider using the Cloudflare [`/cdn-cgi/trace`](https://cloudflare.com/cdn-cgi/trace) API instead of timeapi.io, which may not be freely accessible over the long term.

**Comment by BlackDex** [comment]
> I'm not sure renaming `Items` to `Ciphers` in the UI is an improvement. IMO, this is an overly technical term that may cause confusion, and Bitwarden itself uses the "items" term in their UI and user-facing docs.
> 

Maybe we should call it `Vault Items` then? That is more descriptive.

> Also, you might consider using the Cloudflare [`/cdn-cgi/trace`](https://cloudflare.com/cdn-cgi/trace) API instead of timeapi.io, which may not be freely accessible over the long term.

Thanks for the tip. While i think timeapi.io should be enough. It's not that people keep bashing the diagnostics page. And on there site they claim to keep a free plan available, which I think would suffice. But in case it's not, we can switch easily.

**Comment by jjlin** [comment]
> > I'm not sure renaming `Items` to `Ciphers` in the UI is an improvement. IMO, this is an overly technical term that may cause confusion, and Bitwarden itself uses the "items" term in their UI and user-facing docs.
> 
> Maybe we should call it `Vault Items` then? That is more descriptive.

Sounds fine to me.

> > Also, you might consider using the Cloudflare [`/cdn-cgi/trace`](https://cloudflare.com/cdn-cgi/trace) API instead of timeapi.io, which may not be freely accessible over the long term.
> 
> Thanks for the tip. While i think timeapi.io should be enough. It's not that people keep bashing the diagnostics page. And on there site they claim to keep a free plan available, which I think would suffice. But in case it's not, we can switch easily.

I assume a free plan means that an API key would need to be provided, though.

**Comment by BlackDex** [comment]
> > > I'm not sure renaming `Items` to `Ciphers` in the UI is an improvement. IMO, this is an overly technical term that may cause confusion, and Bitwarden itself uses the "items" term in their UI and user-facing docs.
> > 
> > 
> > Maybe we should call it `Vault Items` then? That is more descriptive.
> 
> Sounds fine to me.
> 
> > > Also, you might consider using the Cloudflare [`/cdn-cgi/trace`](https://cloudflare.com/cdn-cgi/trace) API instead of timeapi.io, which may not be freely accessible over the long term.
> > 
> > 
> > Thanks for the tip. While i think timeapi.io should be enough. It's not that people keep bashing the diagnostics page. And on there site they claim to keep a free plan available, which I think would suffice. But in case it's not, we can switch easily.
> 
> I assume a free plan means that an API key would need to be provided, though.

That might be a possibility indeed. But they have a 180 days of grace period for changing the API and depreciate it, that should be more then enough time.

**Comment by tessus** [comment]
I never understood why they would call notes, logins, identity, and cards: ciphers. A cipher is an algorithm for performing encryption or decryption, not a password or any of the other item types.

I am not sure "Vault Items" is an improvement, because where else would the items be?

So there a few terms that fit the profile:

- items
- entries
- records

Anything is better than cipher. ;-)

**Comment by tessus** [comment]
@BlackDex Btw, is it ok to comment on a merged PR or shall I rather create a new discussion?

**Comment by BlackDex** [comment]
This is fine. Ill take these comments into a new pr with some other changes.

**Pull request merged**
