### PR TITLE
Update admin interface

### PR DESCRIPTION
**Pull request by BlackDex**
- Updated datatables
- Set Cookie Secure flag if the connection is https
- Prevent possible XSS via Organization Name
  Converted all `innerHTML` and `innerText` to the Safe Sink version `textContent`
- Removed `jsesc` function as handlebars escapes all these chars already and more by default

### CODE REVIEW

**Review by lukasj98 — APPROVED** [review]

**Comment by tessus** [comment]
> Set Cookie Secure flag if the connection is https

What happens, if https is terminated at the reverse proxy (and vw is running as http)?

**Comment by BlackDex** [comment]
That is where the header check is for.
`X-Forwarded-Proto`, which is already used in an other function.

**Comment by BlackDex** [comment]
It is a commonly used header https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html#x-forwarded-proto

**Comment by tessus** [comment]
I know that header, I am just asking what happens, if the server thinks it's running under TLS, but in reality it is running as http. e.g. http won't understand TLS traffic.
In a reverse proxy situation with vw not using TLS, vw is running as a http server.

**Comment by BlackDex** [comment]
Then it will not set the secure flag, same as it is now.
So nothing changes in that case.
But again, that is where that header is for, that is something the reverse proxy needs to sent and provide the correct value.

**Review by dani-garcia — APPROVED** [review]

**Pull request merged**
