### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by benarmstead**
Update cargo dependencies

### CODE REVIEW

**Comment by BlackDex** [comment]
Thx for the contribution.
But i'm missing the Cargo.toml changes to represent the updated versions there.
While this isn't strictly necessary, it does give a better view on which versions are used by this project it self, instead of having to shift through both Cargo.toml and Cargo.lock.

I normally do a `cargo update --dry-run` and update the versions in the Cargo.toml file where needed and after that do a run without the `--dry-run` to update the Cargo.lock.

**Comment by benarmstead** [comment]
Ok no problem, I will do that now and get back to you

**Comment by benarmstead** [comment]
Think I have done it

**Review by BlackDex — APPROVED** [review]

**Comment by jjlin** [comment]
Was there some specific issue addressed by these updates?

**Comment by BlackDex** [comment]
What i saw was the OpenSSL libraries that were updated which were released because of CVE's (See: https://rustsec.org/advisories/RUSTSEC-2021-0098 & https://www.openssl.org/news/vulnerabilities.html)

**Comment by jjlin** [comment]
Ok, it would be nice to have this in the commit or PR description instead of a vague message

**Comment by BlackDex** [comment]
Well, the dep updates are sometimes also done without any specific descriptions besides, just updating it, and sometimes a small remark about updating code, but thats it..

But good item to think about for the future :).

**Comment by jjlin** [comment]
That's more acceptable if done as part of the normal course of project maintenance by established maintainers, but my main point is I don't want to see random unjustified dep updates by unfamiliar people.

**Comment by BlackDex** [comment]
Very valid point indeed.

**Comment by BlackDex** [comment]
Also, that is where reviewing a PR comes in. If it's reviewed correctly then it shouldn't matter if it's from someone new or had done multiple PR's already. Dismissing a PR just because someone never pushed one before is not what we want i think.

**Comment by jjlin** [comment]
I welcome quality contributions from anyone, new or old. But to be blunt, this is not a quality contribution. It has little to no value, because:

1. Dependency updates are going to get done in the normal course of development anyway, such as when someone makes a change that requires adding/removing/updating libraries, or when @dani-garcia prepares for a new release.

2. Dependency updates are not always an improvement. They can introduce regressions, and when the PR is coming from someone new, it's unknown if that person has done any testing on the result, or is even reasonably knowledgeable about how to do such testing.

So I don't think that PRs that update dependencies just for the sake of updating them should be accepted; there needs to be specific justification. For example, it's fine if there's a dependency that should be updated promptly because of a security issue, but that needs to be called out specifically. Otherwise, dependencies are updated all the time, so there could conceivably be "update dependencies" PRs coming in every few days, and that's not something I want to encourage.

Regarding your contention that the source of a PR doesn't matter if it's "reviewed correctly", I agree in theory. But in practice, time and attention are limited and not all PRs are reviewed as carefully as others. In particular, there's a tendency for PRs with a lot of generated changes (such as lock files, updates to JS libraries, etc.) to be reviewed less carefully, simply because it's tedious work. This is just human nature and won't change in the foreseeable future. Therefore, the source of a PR can matter in practice, and when possible, I prefer that PRs for changes like this to be done by people who are not new to the project.

**Comment by BlackDex** [comment]
All valid points and i agree.

If it makes you feel a bit better, i had a local branch already with some updated libs and i noticed the same versions. And thus i tested it my self already. I only didn't noticed the cve before on the OpenSSL and therefore decided to merge.

I should have mentioned that in my comments I am sorry for the lack of my communication on that part. I will keep that in mind.

I am also glad you are make a point of this especially for software like Vaultwarden which handels sensitive information.

**Pull request merged**
