### PR TITLE
Allow FireFox relay in CSP.

### PR DESCRIPTION
**Pull request by BlackDex**
This PR is needed for https://github.com/dani-garcia/bw_web_builds/pull/71
Without this the web-vault will refuse to make calls to the FireFox Relay API.

Also fixed a small issue with the pre-commit config.

### CODE REVIEW

**Review by GeekCornerGH — APPROVED** [review]

**Comment by BlackDex** [comment]
I Updated the comments to give a bit more information, since this is security related, lets have some better info there.

**Comment by Flash1232** [comment]
Just on a sidenote: AnonAddy (maybe also SimpleLogin) allows for self-hosted instances. Is there any chance this whitelist could be made configurable?

**Comment by BlackDex** [comment]
> Just on a sidenote: AnonAddy (maybe also SimpleLogin) allows for self-hosted instances. Is there any chance this whitelist could be made configurable?

That is not an option for now, since Bitwarden does not support self-hosted instances of those services. They only allow the public services. There is no way to configure this in Bitwarden (As far as i could tell).

**Comment by KainAlive** [comment]
Is Firefox Relay supported in Vaultwarden? I'm using the latest docker image and only get "AnonAddy", "Fastmail" and "SimpleLogin" as choices.

**Comment by BlackDex** [comment]
> Is Firefox Relay supported in Vaultwarden? I'm using the latest docker image and only get "AnonAddy", "Fastmail" and "SimpleLogin" as choices.

That doesn't work for self hosted environments, only Bitwarden Cloud.

**Pull request merged**
