### PR TITLE
feat: Working passkeys storage

### PR DESCRIPTION
**Pull request by GeekCornerGH**
Revert changes in #3593 and make them work with Browser plugin 2023.10.1

### CODE REVIEW

**Comment by Justus-D** [comment]
I just wanted to confirm, that the current stable version of Vaultwarden (1.29.2) seems to be working with passkeys. I modified the response of `/api/config` to include `"fido2-vault-credentials": true` and I was able to store passkeys with the current version of the browser extension (2023.10.1).

**Comment by tessus** [comment]
Interesting. I am wondering how they are stored in the db. Maybe they are reusing the password field.

**Comment by Justus-D** [comment]
> Interesting. I am wondering how they are stored in the db. Maybe they are reusing the password field.

Passkeys are stored in the login cipher. So in the same field as the password and the URL of the login.

**Review by dani-garcia — APPROVED** [review]
Sometimes the fact that I decided to dump the cipher data from the clients directly into the column as JSON ends up being really convenient, nice haha

**Pull request merged**
