### PR TITLE
Improve sync speed and updated dep. versions

### PR DESCRIPTION
**Pull request by BlackDex**
Improved sync speed by resolving the N+1 query issues.
Solves #1402 and Solves #1453

With this change there is just one query done to retreive all the important data, and matching is done in-code/memory.
With a very large database the sync time went down about 3 times.

Also updated misc crates and Github Actions versions.

### CODE REVIEW

**Comment by manofthepeace** [comment]
Just wondering if this crate could be used https://crates.io/crates/tokio_cron_scheduler instead of a not so maintained version of the current job_scheduler. It is based on job_scheduler, and seem actively maintained for now at least.

**Comment by BlackDex** [comment]
Small update.

I have fixed all the full-sync code to use the the `CipherSyncData`.
Depending on how many ciphers, collections and organizations a user has access to, with my tests I got a speedup of nearly 3x using this code.

I still checking for other optimizations to see if i can add those.

**Comment by BlackDex** [comment]
Did some final checking and this looks like merge-ready.
Deleting multiple ciphers can still be optimized, but that currently is very entwined with functions calling other functions which could also call other functions.

There are also some optimizations which could be done with web-sockets, but also that need some more work and probably better for an other PR.

**Comment by dani-garcia** [comment]
Thanks for your work @BlackDex!

**Comment by bendem** [comment]
Just wanted to say that this is the greatest thing. Loading the home list went down from 4-8s to <0.5s. Best optimisation since the bread slicer!

**Pull request merged**
