### PR TITLE
docs: Add basic contributing details to README

### PR DESCRIPTION
**Pull request by domdomegg**
As a new contributor (maybe just because I haven't used Rust before) I didn't easily see how to get started.

If this is too much for the README, happy just to have a link to the wiki page on building the binary which I only found after quite some digging (as I initially searched 'contributing' and 'developing').

### CODE REVIEW

**Comment by BlackDex** [comment]
A link to the wiki would also be a good addition, because there it also describes what dependencies there are needed.

**Comment by jjlin** [comment]
Instead of adding all this inline, I think it would be better to just link to an appropriate wiki page (updating or creating it as needed). In general, the README.md has not been that well-maintained since there is a much higher barrier to making changes.

**Review by williamdes — APPROVED** [review]

**Review by Ornias1993 — CHANGES_REQUESTED** [review]
A github standard `CONTRUBUTING` file and both a wiki and `CONTRIBUTING` link in the readme seems to be beter suited for this...

**Comment by BlackDex** [comment]
I'm going to close this PR. I agree with @jjlin that this better suited to be placed somewhere else like in a good wiki page, or maybe even the github standard CONTRUBUTING.

Feel free to create a new PR, or update the wiki :smile:

**Pull request closed without merging**
